version: '3.7'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true