name: api

on: push

jobs:
  test:
    runs-on: ['ubuntu-latest']
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Download test dependencies
      uses: teddyking/dependency-action@master
      with:
        deps: https://storage.googleapis.com/oauth2l/latest/linux_amd64.tgz
    - name: Create OAuth2l command
      run: echo "alias oauth2l=\"cd ~/Downloads/darwin_amd64 && ./oauth2l\"" >> "$HOME/.bash_profile" && source $HOME/.bash_profile
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./web/api
