name: api

on: push

jobs:
  test:
    runs-on: ['ubuntu-latest']
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" 
    - name: Install oauth2l
      run: brew install oauth2l
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./web/api
